FROM node:20-alpine3.20 as build
USER node
WORKDIR  /app
COPY package.json .
RUN npm ci 
COPY . .
RUN npm run build


FROM nginx:1.27.0-alpine as final
WORKDIR /app
COPY --from=build /app/dist /usr/share/nginx/html/