FROM node:20-alpine3.20 AS build
USER node
WORKDIR  /app
COPY package*.json .
RUN npm ci 
COPY . .
RUN npm run build


FROM nginx:1.27.0-alpine AS final
WORKDIR /app
COPY --from=build /app/dist /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]