services:
 postgres: 
   image: postgres:alpine
   restart: always
   environment:
    LC_ALL: C.UTF-8
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
   volumes:
     - pgdata:/var/lib/postgresql/data
     - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
   ports: 
   - "5432:5432"
   healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: