version: '3'
services:
 postgres: 
   image: postgres:alpine
   restart: always
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: lreplass
   volumes:
     - pgdata:/var/lib/postgresql/data
   ports: 
   - "5432:5432"
volumes:
  pgdata: