FROM node:20-alpine3.20 AS installer
USER node
WORKDIR  /app
COPY package*.json .
RUN npm ci

FROM node:20-alpine3.20 AS final
USER node
WORKDIR  /app
COPY --from=installer /app /app
COPY . .

CMD ["node", "index.js"]

EXPOSE 3000